# Generated by Django 4.2.30 on 2026-06-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='futsal',
            name='is_closed_today',
            field=models.BooleanField(default=False),
        ),
    ]
