# Generated by Django 4.2.30 on 2026-06-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_futsal_is_closed_today'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courtimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='courtimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courts/'),
        ),
        migrations.AddField(
            model_name='futsal',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='futsal',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='futsal',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
